# -*- coding: utf-8 -*-

name: Build documentation

on:
  push:
    branches:
      - '*'
    tags:
      - '*'

jobs:
  build-distributions:
    runs-on: ubuntu-latest
    name: Build documentation
    steps:
      - name: Clone repository
        uses: actions/checkout@v2
        with:
          # Fetch depth of 0 means the entire git history will be retrieved
          # This is slower, but if you don't do this, it will create a single-commit 'shallow' clone
          # A shallow clone only has one commit, so this would make the version numbers look like X.Y.Za1 instead of the real commit number.
          # See https://git-scm.com/docs/shallow
          fetch-depth: 0

      - name: Install and set up Python ${{ matrix.python-version }} ${{ matrix.python-arch }}
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
          architecture: 'x64'

      - name: Install meta dependencies
        shell: bash
        run: |
          python -m pip install -U pip setuptools wheel

      - name: Install library
        shell: bash
        run: |
          python -m pip install -U .[docs,voice]

      - name: Build documentation
        shell: bash
        run: |
          cd docs
          make html
          cd ..

      - name: Upload documentation
        uses: actions/upload-artifact@v2
        with:
          name: documentation
          path: docs/_build/*
